### ISSUE TITLE
首頁

### ISSUE THREAD

**Issue by chikatsai** [town-intelligent-beta/eID#1]

**Comment by chikatsai** [comment]
@ssutsen 
說明:
1. 邊框色號 **FFF38D** 
2. eID logo 改為[連結](https://drive.google.com/file/d/1B08w4qI9vvUIa_AKui2RWJung7XlAoSm/view?usp=sharing)

**Comment by ssutsen** [comment]
https://github.com/town-intelligent-beta/eID/pull/18

**Comment by yillkid** [comment]
## Description
準備進行 Code Review 與測試

## Deploy

#### Standalone:
- http://beta-eid.4impact.cc/

**Comment by yillkid** [comment]
@chikatsai 請你測試一下 [website](http://beta-eid.4impact.cc/) : 
1. 首頁圖文
2. RWD

之後我們針對 RWD 大型顯示裝置討論一下。

## 擷圖 (大型顯示器)
![Image](https://github.com/user-attachments/assets/25c46849-c16b-4abf-a658-9f1dd0535e46)

## 擷圖 (小型顯示器)
![Image](https://github.com/user-attachments/assets/3cca8f65-465c-47ae-a0a6-af821e0593b3)

## 擷圖 (大型顯示器 (RWD 修正後) )
![Image](https://github.com/user-attachments/assets/2a7a16a2-c93a-4fac-98ae-445e9584e391)

## 擷圖 (小型顯示器)
![Image](https://github.com/user-attachments/assets/86f0e3b4-bde6-464f-b193-031bb2d6aa69)

**Comment by yillkid** [comment]
@chikatsai Ready to test : http://beta-eid.4impact.cc/

**Comment by chikatsai** [comment]
> [@chikatsai](https://github.com/chikatsai) Ready to test : http://beta-eid.4impact.cc/

@yillkid 大小型顯示器皆 OK
